// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package gov.nist.csd.pm.pap.op.operation.proto;

/**
 * Protobuf type {@code CreateAdminOperationOp}
 */
public final class CreateAdminOperationOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateAdminOperationOp)
    CreateAdminOperationOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateAdminOperationOp.newBuilder() to construct.
  private CreateAdminOperationOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateAdminOperationOp() {
    pml_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateAdminOperationOp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateAdminOperationOp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            pml_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_CreateAdminOperationOp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_CreateAdminOperationOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.class, gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.Builder.class);
  }

  public static final int PML_FIELD_NUMBER = 1;
  private volatile java.lang.Object pml_;
  /**
   * <code>string pml = 1;</code>
   * @return The pml.
   */
  @java.lang.Override
  public java.lang.String getPml() {
    java.lang.Object ref = pml_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pml_ = s;
      return s;
    }
  }
  /**
   * <code>string pml = 1;</code>
   * @return The bytes for pml.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPmlBytes() {
    java.lang.Object ref = pml_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pml_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pml_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pml_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pml_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pml_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp)) {
      return super.equals(obj);
    }
    gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp other = (gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp) obj;

    if (!getPml()
        .equals(other.getPml())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PML_FIELD_NUMBER;
    hash = (53 * hash) + getPml().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateAdminOperationOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateAdminOperationOp)
      gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_CreateAdminOperationOp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_CreateAdminOperationOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.class, gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.Builder.class);
    }

    // Construct using gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pml_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_CreateAdminOperationOp_descriptor;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp getDefaultInstanceForType() {
      return gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.getDefaultInstance();
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp build() {
      gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp buildPartial() {
      gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp result = new gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp(this);
      result.pml_ = pml_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp) {
        return mergeFrom((gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp other) {
      if (other == gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp.getDefaultInstance()) return this;
      if (!other.getPml().isEmpty()) {
        pml_ = other.pml_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object pml_ = "";
    /**
     * <code>string pml = 1;</code>
     * @return The pml.
     */
    public java.lang.String getPml() {
      java.lang.Object ref = pml_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pml_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pml = 1;</code>
     * @return The bytes for pml.
     */
    public com.google.protobuf.ByteString
        getPmlBytes() {
      java.lang.Object ref = pml_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pml_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pml = 1;</code>
     * @param value The pml to set.
     * @return This builder for chaining.
     */
    public Builder setPml(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pml_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pml = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPml() {
      
      pml_ = getDefaultInstance().getPml();
      onChanged();
      return this;
    }
    /**
     * <code>string pml = 1;</code>
     * @param value The bytes for pml to set.
     * @return This builder for chaining.
     */
    public Builder setPmlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pml_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateAdminOperationOp)
  }

  // @@protoc_insertion_point(class_scope:CreateAdminOperationOp)
  private static final gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp();
  }

  public static gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateAdminOperationOp>
      PARSER = new com.google.protobuf.AbstractParser<CreateAdminOperationOp>() {
    @java.lang.Override
    public CreateAdminOperationOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateAdminOperationOp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateAdminOperationOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateAdminOperationOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.nist.csd.pm.pap.op.operation.proto.CreateAdminOperationOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

