// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package gov.nist.csd.pm.pap.op.operation.proto;

public interface CreateAdminOperationOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateAdminOperationOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pml = 1;</code>
   * @return The pml.
   */
  java.lang.String getPml();
  /**
   * <code>string pml = 1;</code>
   * @return The bytes for pml.
   */
  com.google.protobuf.ByteString
      getPmlBytes();
}
