// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package gov.nist.csd.pm.pap.op.operation.proto;

public final class OperationProto {
  private OperationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAdminOperationOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAdminOperationOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteAdminOperationOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteAdminOperationOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetResourceOperationsOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetResourceOperationsOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017operation.proto\"%\n\026CreateAdminOperatio" +
      "nOp\022\013\n\003pml\030\001 \001(\t\"&\n\026DeleteAdminOperation" +
      "Op\022\014\n\004name\030\001 \001(\t\"-\n\027SetResourceOperation" +
      "sOp\022\022\n\noperations\030\001 \003(\tB:\n&gov.nist.csd." +
      "pm.pap.op.operation.protoB\016OperationProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateAdminOperationOp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateAdminOperationOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAdminOperationOp_descriptor,
        new java.lang.String[] { "Pml", });
    internal_static_DeleteAdminOperationOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeleteAdminOperationOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteAdminOperationOp_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_SetResourceOperationsOp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SetResourceOperationsOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetResourceOperationsOp_descriptor,
        new java.lang.String[] { "Operations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
