// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package gov.nist.csd.pm.pap.op.operation.proto;

public interface SetResourceOperationsOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetResourceOperationsOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string operations = 1;</code>
   * @return A list containing the operations.
   */
  java.util.List<java.lang.String>
      getOperationsList();
  /**
   * <code>repeated string operations = 1;</code>
   * @return The count of operations.
   */
  int getOperationsCount();
  /**
   * <code>repeated string operations = 1;</code>
   * @param index The index of the element to return.
   * @return The operations at the given index.
   */
  java.lang.String getOperations(int index);
  /**
   * <code>repeated string operations = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the operations at the given index.
   */
  com.google.protobuf.ByteString
      getOperationsBytes(int index);
}
