// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package gov.nist.csd.pm.pap.op.operation.proto;

/**
 * Protobuf type {@code SetResourceOperationsOp}
 */
public final class SetResourceOperationsOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SetResourceOperationsOp)
    SetResourceOperationsOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetResourceOperationsOp.newBuilder() to construct.
  private SetResourceOperationsOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetResourceOperationsOp() {
    operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetResourceOperationsOp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetResourceOperationsOp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              operations_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            operations_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        operations_ = operations_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_SetResourceOperationsOp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_SetResourceOperationsOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.class, gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.Builder.class);
  }

  public static final int OPERATIONS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList operations_;
  /**
   * <code>repeated string operations = 1;</code>
   * @return A list containing the operations.
   */
  public com.google.protobuf.ProtocolStringList
      getOperationsList() {
    return operations_;
  }
  /**
   * <code>repeated string operations = 1;</code>
   * @return The count of operations.
   */
  public int getOperationsCount() {
    return operations_.size();
  }
  /**
   * <code>repeated string operations = 1;</code>
   * @param index The index of the element to return.
   * @return The operations at the given index.
   */
  public java.lang.String getOperations(int index) {
    return operations_.get(index);
  }
  /**
   * <code>repeated string operations = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the operations at the given index.
   */
  public com.google.protobuf.ByteString
      getOperationsBytes(int index) {
    return operations_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < operations_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operations_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < operations_.size(); i++) {
        dataSize += computeStringSizeNoTag(operations_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOperationsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp)) {
      return super.equals(obj);
    }
    gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp other = (gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp) obj;

    if (!getOperationsList()
        .equals(other.getOperationsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOperationsCount() > 0) {
      hash = (37 * hash) + OPERATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOperationsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SetResourceOperationsOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SetResourceOperationsOp)
      gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_SetResourceOperationsOp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_SetResourceOperationsOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.class, gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.Builder.class);
    }

    // Construct using gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.nist.csd.pm.pap.op.operation.proto.OperationProto.internal_static_SetResourceOperationsOp_descriptor;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp getDefaultInstanceForType() {
      return gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.getDefaultInstance();
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp build() {
      gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp buildPartial() {
      gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp result = new gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        operations_ = operations_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.operations_ = operations_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp) {
        return mergeFrom((gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp other) {
      if (other == gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp.getDefaultInstance()) return this;
      if (!other.operations_.isEmpty()) {
        if (operations_.isEmpty()) {
          operations_ = other.operations_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOperationsIsMutable();
          operations_.addAll(other.operations_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOperationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        operations_ = new com.google.protobuf.LazyStringArrayList(operations_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @return A list containing the operations.
     */
    public com.google.protobuf.ProtocolStringList
        getOperationsList() {
      return operations_.getUnmodifiableView();
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @return The count of operations.
     */
    public int getOperationsCount() {
      return operations_.size();
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param index The index of the element to return.
     * @return The operations at the given index.
     */
    public java.lang.String getOperations(int index) {
      return operations_.get(index);
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the operations at the given index.
     */
    public com.google.protobuf.ByteString
        getOperationsBytes(int index) {
      return operations_.getByteString(index);
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param index The index to set the value at.
     * @param value The operations to set.
     * @return This builder for chaining.
     */
    public Builder setOperations(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOperationsIsMutable();
      operations_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param value The operations to add.
     * @return This builder for chaining.
     */
    public Builder addOperations(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOperationsIsMutable();
      operations_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param values The operations to add.
     * @return This builder for chaining.
     */
    public Builder addAllOperations(
        java.lang.Iterable<java.lang.String> values) {
      ensureOperationsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, operations_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperations() {
      operations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string operations = 1;</code>
     * @param value The bytes of the operations to add.
     * @return This builder for chaining.
     */
    public Builder addOperationsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOperationsIsMutable();
      operations_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SetResourceOperationsOp)
  }

  // @@protoc_insertion_point(class_scope:SetResourceOperationsOp)
  private static final gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp();
  }

  public static gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetResourceOperationsOp>
      PARSER = new com.google.protobuf.AbstractParser<SetResourceOperationsOp>() {
    @java.lang.Override
    public SetResourceOperationsOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetResourceOperationsOp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetResourceOperationsOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetResourceOperationsOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.nist.csd.pm.pap.op.operation.proto.SetResourceOperationsOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

