// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obligation.proto

package gov.nist.csd.pm.pap.op.obligation.proto;

public interface CreateObligationOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateObligationOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string author = 2;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 2;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string pml = 3;</code>
   * @return The pml.
   */
  java.lang.String getPml();
  /**
   * <code>string pml = 3;</code>
   * @return The bytes for pml.
   */
  com.google.protobuf.ByteString
      getPmlBytes();
}
