// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: obligation.proto

package gov.nist.csd.pm.pap.op.obligation.proto;

public final class ObligationProto {
  private ObligationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateObligationOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateObligationOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteObligationOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteObligationOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020obligation.proto\"?\n\022CreateObligationOp" +
      "\022\014\n\004name\030\001 \001(\t\022\016\n\006author\030\002 \001(\t\022\013\n\003pml\030\003 " +
      "\001(\t\"\"\n\022DeleteObligationOp\022\014\n\004name\030\001 \001(\tB" +
      "<\n\'gov.nist.csd.pm.pap.op.obligation.pro" +
      "toB\017ObligationProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateObligationOp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateObligationOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateObligationOp_descriptor,
        new java.lang.String[] { "Name", "Author", "Pml", });
    internal_static_DeleteObligationOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeleteObligationOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteObligationOp_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
