// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routine.proto

package gov.nist.csd.pm.pap.op.routine.proto;

public interface CreateAdminRoutineOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateAdminRoutineOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pml = 1;</code>
   * @return The pml.
   */
  java.lang.String getPml();
  /**
   * <code>string pml = 1;</code>
   * @return The bytes for pml.
   */
  com.google.protobuf.ByteString
      getPmlBytes();
}
