// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: routine.proto

package gov.nist.csd.pm.pap.op.routine.proto;

public final class RoutineProto {
  private RoutineProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAdminRoutineOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAdminRoutineOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteAdminRoutineOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteAdminRoutineOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rroutine.proto\"#\n\024CreateAdminRoutineOp\022" +
      "\013\n\003pml\030\001 \001(\t\"$\n\024DeleteAdminRoutineOp\022\014\n\004" +
      "name\030\001 \001(\tB6\n$gov.nist.csd.pm.pap.op.rou" +
      "tine.protoB\014RoutineProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateAdminRoutineOp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateAdminRoutineOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAdminRoutineOp_descriptor,
        new java.lang.String[] { "Pml", });
    internal_static_DeleteAdminRoutineOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeleteAdminRoutineOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteAdminRoutineOp_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
