// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

package gov.nist.csd.pm.pap.op.graph.proto;

public interface AssociateOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AssociateOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ua = 1;</code>
   * @return The ua.
   */
  java.lang.String getUa();
  /**
   * <code>string ua = 1;</code>
   * @return The bytes for ua.
   */
  com.google.protobuf.ByteString
      getUaBytes();

  /**
   * <code>string target = 2;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 2;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <code>repeated string arset = 3;</code>
   * @return A list containing the arset.
   */
  java.util.List<java.lang.String>
      getArsetList();
  /**
   * <code>repeated string arset = 3;</code>
   * @return The count of arset.
   */
  int getArsetCount();
  /**
   * <code>repeated string arset = 3;</code>
   * @param index The index of the element to return.
   * @return The arset at the given index.
   */
  java.lang.String getArset(int index);
  /**
   * <code>repeated string arset = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the arset at the given index.
   */
  com.google.protobuf.ByteString
      getArsetBytes(int index);
}
