// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

package gov.nist.csd.pm.pap.op.graph.proto;

public interface CreateObjectOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateObjectOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string descendants = 2;</code>
   * @return A list containing the descendants.
   */
  java.util.List<java.lang.String>
      getDescendantsList();
  /**
   * <code>repeated string descendants = 2;</code>
   * @return The count of descendants.
   */
  int getDescendantsCount();
  /**
   * <code>repeated string descendants = 2;</code>
   * @param index The index of the element to return.
   * @return The descendants at the given index.
   */
  java.lang.String getDescendants(int index);
  /**
   * <code>repeated string descendants = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the descendants at the given index.
   */
  com.google.protobuf.ByteString
      getDescendantsBytes(int index);
}
