// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graph.proto

package gov.nist.csd.pm.pap.op.graph.proto;

public final class GraphProto {
  private GraphProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AssignOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AssignOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AssociateOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AssociateOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePolicyClassOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreatePolicyClassOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserAttributeOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserAttributeOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateObjectAttributeOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateObjectAttributeOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateObjectOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateObjectOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeassignOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeassignOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteNodeOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteNodeOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetNodePropertiesOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetNodePropertiesOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetNodePropertiesOp_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetNodePropertiesOp_PropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013graph.proto\"2\n\010AssignOp\022\021\n\tascendant\030\001" +
      " \001(\t\022\023\n\013descendants\030\002 \003(\t\"8\n\013AssociateOp" +
      "\022\n\n\002ua\030\001 \001(\t\022\016\n\006target\030\002 \001(\t\022\r\n\005arset\030\003 " +
      "\003(\t\"#\n\023CreatePolicyClassOp\022\014\n\004name\030\001 \001(\t" +
      "\":\n\025CreateUserAttributeOp\022\014\n\004name\030\001 \001(\t\022" +
      "\023\n\013descendants\030\002 \003(\t\"<\n\027CreateObjectAttr" +
      "ibuteOp\022\014\n\004name\030\001 \001(\t\022\023\n\013descendants\030\002 \003" +
      "(\t\"1\n\014CreateUserOp\022\014\n\004name\030\001 \001(\t\022\023\n\013desc" +
      "endants\030\002 \003(\t\"3\n\016CreateObjectOp\022\014\n\004name\030" +
      "\001 \001(\t\022\023\n\013descendants\030\002 \003(\t\"4\n\nDeassignOp" +
      "\022\021\n\tascendant\030\001 \001(\t\022\023\n\013descendants\030\002 \003(\t" +
      "\"\034\n\014DeleteNodeOp\022\014\n\004name\030\001 \001(\t\"\220\001\n\023SetNo" +
      "dePropertiesOp\022\014\n\004name\030\001 \001(\t\0228\n\nproperti" +
      "es\030\002 \003(\0132$.SetNodePropertiesOp.Propertie" +
      "sEntry\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001B2\n\"gov.nist.csd.pm.pap" +
      ".op.graph.protoB\nGraphProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AssignOp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AssignOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AssignOp_descriptor,
        new java.lang.String[] { "Ascendant", "Descendants", });
    internal_static_AssociateOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AssociateOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AssociateOp_descriptor,
        new java.lang.String[] { "Ua", "Target", "Arset", });
    internal_static_CreatePolicyClassOp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreatePolicyClassOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreatePolicyClassOp_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_CreateUserAttributeOp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CreateUserAttributeOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserAttributeOp_descriptor,
        new java.lang.String[] { "Name", "Descendants", });
    internal_static_CreateObjectAttributeOp_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CreateObjectAttributeOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateObjectAttributeOp_descriptor,
        new java.lang.String[] { "Name", "Descendants", });
    internal_static_CreateUserOp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CreateUserOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserOp_descriptor,
        new java.lang.String[] { "Name", "Descendants", });
    internal_static_CreateObjectOp_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CreateObjectOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateObjectOp_descriptor,
        new java.lang.String[] { "Name", "Descendants", });
    internal_static_DeassignOp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_DeassignOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeassignOp_descriptor,
        new java.lang.String[] { "Ascendant", "Descendants", });
    internal_static_DeleteNodeOp_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_DeleteNodeOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteNodeOp_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_SetNodePropertiesOp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SetNodePropertiesOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetNodePropertiesOp_descriptor,
        new java.lang.String[] { "Name", "Properties", });
    internal_static_SetNodePropertiesOp_PropertiesEntry_descriptor =
      internal_static_SetNodePropertiesOp_descriptor.getNestedTypes().get(0);
    internal_static_SetNodePropertiesOp_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetNodePropertiesOp_PropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
