// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prohibitions.proto

package gov.nist.csd.pm.pap.op.prohibition.proto;

/**
 * Protobuf type {@code CreateProhibitionOp}
 */
public final class CreateProhibitionOp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateProhibitionOp)
    CreateProhibitionOpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateProhibitionOp.newBuilder() to construct.
  private CreateProhibitionOp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateProhibitionOp() {
    name_ = "";
    subject_ = "";
    subjectType_ = "";
    arset_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateProhibitionOp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateProhibitionOp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            subject_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            subjectType_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              arset_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            arset_.add(s);
            break;
          }
          case 40: {

            intersection_ = input.readBool();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              containerConditions_ = com.google.protobuf.MapField.newMapField(
                  ContainerConditionsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
            containerConditions__ = input.readMessage(
                ContainerConditionsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            containerConditions_.getMutableMap().put(
                containerConditions__.getKey(), containerConditions__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        arset_ = arset_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 6:
        return internalGetContainerConditions();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.class, gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 2;
  private volatile java.lang.Object subject_;
  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  @java.lang.Override
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object subjectType_;
  /**
   * <code>string subject_type = 3;</code>
   * @return The subjectType.
   */
  @java.lang.Override
  public java.lang.String getSubjectType() {
    java.lang.Object ref = subjectType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectType_ = s;
      return s;
    }
  }
  /**
   * <code>string subject_type = 3;</code>
   * @return The bytes for subjectType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectTypeBytes() {
    java.lang.Object ref = subjectType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARSET_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList arset_;
  /**
   * <code>repeated string arset = 4;</code>
   * @return A list containing the arset.
   */
  public com.google.protobuf.ProtocolStringList
      getArsetList() {
    return arset_;
  }
  /**
   * <code>repeated string arset = 4;</code>
   * @return The count of arset.
   */
  public int getArsetCount() {
    return arset_.size();
  }
  /**
   * <code>repeated string arset = 4;</code>
   * @param index The index of the element to return.
   * @return The arset at the given index.
   */
  public java.lang.String getArset(int index) {
    return arset_.get(index);
  }
  /**
   * <code>repeated string arset = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the arset at the given index.
   */
  public com.google.protobuf.ByteString
      getArsetBytes(int index) {
    return arset_.getByteString(index);
  }

  public static final int INTERSECTION_FIELD_NUMBER = 5;
  private boolean intersection_;
  /**
   * <code>bool intersection = 5;</code>
   * @return The intersection.
   */
  @java.lang.Override
  public boolean getIntersection() {
    return intersection_;
  }

  public static final int CONTAINER_CONDITIONS_FIELD_NUMBER = 6;
  private static final class ContainerConditionsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Boolean> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_ContainerConditionsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BOOL,
                false);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Boolean> containerConditions_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
  internalGetContainerConditions() {
    if (containerConditions_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ContainerConditionsDefaultEntryHolder.defaultEntry);
    }
    return containerConditions_;
  }

  public int getContainerConditionsCount() {
    return internalGetContainerConditions().getMap().size();
  }
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */

  @java.lang.Override
  public boolean containsContainerConditions(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetContainerConditions().getMap().containsKey(key);
  }
  /**
   * Use {@link #getContainerConditionsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Boolean> getContainerConditions() {
    return getContainerConditionsMap();
  }
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Boolean> getContainerConditionsMap() {
    return internalGetContainerConditions().getMap();
  }
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  @java.lang.Override

  public boolean getContainerConditionsOrDefault(
      java.lang.String key,
      boolean defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetContainerConditions().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  @java.lang.Override

  public boolean getContainerConditionsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetContainerConditions().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subjectType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subjectType_);
    }
    for (int i = 0; i < arset_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, arset_.getRaw(i));
    }
    if (intersection_ != false) {
      output.writeBool(5, intersection_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetContainerConditions(),
        ContainerConditionsDefaultEntryHolder.defaultEntry,
        6);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subjectType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subjectType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < arset_.size(); i++) {
        dataSize += computeStringSizeNoTag(arset_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getArsetList().size();
    }
    if (intersection_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, intersection_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
         : internalGetContainerConditions().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
      containerConditions__ = ContainerConditionsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, containerConditions__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp)) {
      return super.equals(obj);
    }
    gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp other = (gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getSubject()
        .equals(other.getSubject())) return false;
    if (!getSubjectType()
        .equals(other.getSubjectType())) return false;
    if (!getArsetList()
        .equals(other.getArsetList())) return false;
    if (getIntersection()
        != other.getIntersection()) return false;
    if (!internalGetContainerConditions().equals(
        other.internalGetContainerConditions())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + SUBJECT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSubjectType().hashCode();
    if (getArsetCount() > 0) {
      hash = (37 * hash) + ARSET_FIELD_NUMBER;
      hash = (53 * hash) + getArsetList().hashCode();
    }
    hash = (37 * hash) + INTERSECTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIntersection());
    if (!internalGetContainerConditions().getMap().isEmpty()) {
      hash = (37 * hash) + CONTAINER_CONDITIONS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetContainerConditions().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateProhibitionOp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateProhibitionOp)
      gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetContainerConditions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableContainerConditions();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.class, gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.Builder.class);
    }

    // Construct using gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      subject_ = "";

      subjectType_ = "";

      arset_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      intersection_ = false;

      internalGetMutableContainerConditions().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gov.nist.csd.pm.pap.op.prohibition.proto.ProhibitionProto.internal_static_CreateProhibitionOp_descriptor;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp getDefaultInstanceForType() {
      return gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.getDefaultInstance();
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp build() {
      gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp buildPartial() {
      gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp result = new gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.subject_ = subject_;
      result.subjectType_ = subjectType_;
      if (((bitField0_ & 0x00000001) != 0)) {
        arset_ = arset_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.arset_ = arset_;
      result.intersection_ = intersection_;
      result.containerConditions_ = internalGetContainerConditions();
      result.containerConditions_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp) {
        return mergeFrom((gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp other) {
      if (other == gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        onChanged();
      }
      if (!other.getSubjectType().isEmpty()) {
        subjectType_ = other.subjectType_;
        onChanged();
      }
      if (!other.arset_.isEmpty()) {
        if (arset_.isEmpty()) {
          arset_ = other.arset_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureArsetIsMutable();
          arset_.addAll(other.arset_);
        }
        onChanged();
      }
      if (other.getIntersection() != false) {
        setIntersection(other.getIntersection());
      }
      internalGetMutableContainerConditions().mergeFrom(
          other.internalGetContainerConditions());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     * <code>string subject = 2;</code>
     * @return The subject.
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject = 2;</code>
     * @return The bytes for subject.
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject = 2;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subject_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      
      subject_ = getDefaultInstance().getSubject();
      onChanged();
      return this;
    }
    /**
     * <code>string subject = 2;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subject_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object subjectType_ = "";
    /**
     * <code>string subject_type = 3;</code>
     * @return The subjectType.
     */
    public java.lang.String getSubjectType() {
      java.lang.Object ref = subjectType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subject_type = 3;</code>
     * @return The bytes for subjectType.
     */
    public com.google.protobuf.ByteString
        getSubjectTypeBytes() {
      java.lang.Object ref = subjectType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subject_type = 3;</code>
     * @param value The subjectType to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subjectType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subject_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectType() {
      
      subjectType_ = getDefaultInstance().getSubjectType();
      onChanged();
      return this;
    }
    /**
     * <code>string subject_type = 3;</code>
     * @param value The bytes for subjectType to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subjectType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList arset_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureArsetIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        arset_ = new com.google.protobuf.LazyStringArrayList(arset_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @return A list containing the arset.
     */
    public com.google.protobuf.ProtocolStringList
        getArsetList() {
      return arset_.getUnmodifiableView();
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @return The count of arset.
     */
    public int getArsetCount() {
      return arset_.size();
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param index The index of the element to return.
     * @return The arset at the given index.
     */
    public java.lang.String getArset(int index) {
      return arset_.get(index);
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the arset at the given index.
     */
    public com.google.protobuf.ByteString
        getArsetBytes(int index) {
      return arset_.getByteString(index);
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param index The index to set the value at.
     * @param value The arset to set.
     * @return This builder for chaining.
     */
    public Builder setArset(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArsetIsMutable();
      arset_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param value The arset to add.
     * @return This builder for chaining.
     */
    public Builder addArset(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureArsetIsMutable();
      arset_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param values The arset to add.
     * @return This builder for chaining.
     */
    public Builder addAllArset(
        java.lang.Iterable<java.lang.String> values) {
      ensureArsetIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, arset_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearArset() {
      arset_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string arset = 4;</code>
     * @param value The bytes of the arset to add.
     * @return This builder for chaining.
     */
    public Builder addArsetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureArsetIsMutable();
      arset_.add(value);
      onChanged();
      return this;
    }

    private boolean intersection_ ;
    /**
     * <code>bool intersection = 5;</code>
     * @return The intersection.
     */
    @java.lang.Override
    public boolean getIntersection() {
      return intersection_;
    }
    /**
     * <code>bool intersection = 5;</code>
     * @param value The intersection to set.
     * @return This builder for chaining.
     */
    public Builder setIntersection(boolean value) {
      
      intersection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool intersection = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntersection() {
      
      intersection_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> containerConditions_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetContainerConditions() {
      if (containerConditions_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ContainerConditionsDefaultEntryHolder.defaultEntry);
      }
      return containerConditions_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
    internalGetMutableContainerConditions() {
      onChanged();;
      if (containerConditions_ == null) {
        containerConditions_ = com.google.protobuf.MapField.newMapField(
            ContainerConditionsDefaultEntryHolder.defaultEntry);
      }
      if (!containerConditions_.isMutable()) {
        containerConditions_ = containerConditions_.copy();
      }
      return containerConditions_;
    }

    public int getContainerConditionsCount() {
      return internalGetContainerConditions().getMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */

    @java.lang.Override
    public boolean containsContainerConditions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetContainerConditions().getMap().containsKey(key);
    }
    /**
     * Use {@link #getContainerConditionsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getContainerConditions() {
      return getContainerConditionsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.Boolean> getContainerConditionsMap() {
      return internalGetContainerConditions().getMap();
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */
    @java.lang.Override

    public boolean getContainerConditionsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetContainerConditions().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */
    @java.lang.Override

    public boolean getContainerConditionsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetContainerConditions().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearContainerConditions() {
      internalGetMutableContainerConditions().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */

    public Builder removeContainerConditions(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableContainerConditions().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean>
    getMutableContainerConditions() {
      return internalGetMutableContainerConditions().getMutableMap();
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */
    public Builder putContainerConditions(
        java.lang.String key,
        boolean value) {
      if (key == null) { throw new NullPointerException("map key"); }
      
      internalGetMutableContainerConditions().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
     */

    public Builder putAllContainerConditions(
        java.util.Map<java.lang.String, java.lang.Boolean> values) {
      internalGetMutableContainerConditions().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateProhibitionOp)
  }

  // @@protoc_insertion_point(class_scope:CreateProhibitionOp)
  private static final gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp();
  }

  public static gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateProhibitionOp>
      PARSER = new com.google.protobuf.AbstractParser<CreateProhibitionOp>() {
    @java.lang.Override
    public CreateProhibitionOp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateProhibitionOp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateProhibitionOp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateProhibitionOp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gov.nist.csd.pm.pap.op.prohibition.proto.CreateProhibitionOp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

