// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prohibitions.proto

package gov.nist.csd.pm.pap.op.prohibition.proto;

public interface CreateProhibitionOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateProhibitionOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string subject_type = 3;</code>
   * @return The subjectType.
   */
  java.lang.String getSubjectType();
  /**
   * <code>string subject_type = 3;</code>
   * @return The bytes for subjectType.
   */
  com.google.protobuf.ByteString
      getSubjectTypeBytes();

  /**
   * <code>repeated string arset = 4;</code>
   * @return A list containing the arset.
   */
  java.util.List<java.lang.String>
      getArsetList();
  /**
   * <code>repeated string arset = 4;</code>
   * @return The count of arset.
   */
  int getArsetCount();
  /**
   * <code>repeated string arset = 4;</code>
   * @param index The index of the element to return.
   * @return The arset at the given index.
   */
  java.lang.String getArset(int index);
  /**
   * <code>repeated string arset = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the arset at the given index.
   */
  com.google.protobuf.ByteString
      getArsetBytes(int index);

  /**
   * <code>bool intersection = 5;</code>
   * @return The intersection.
   */
  boolean getIntersection();

  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  int getContainerConditionsCount();
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  boolean containsContainerConditions(
      java.lang.String key);
  /**
   * Use {@link #getContainerConditionsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getContainerConditions();
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getContainerConditionsMap();
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */

  boolean getContainerConditionsOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <code>map&lt;string, bool&gt; container_conditions = 6;</code>
   */

  boolean getContainerConditionsOrThrow(
      java.lang.String key);
}
