// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prohibitions.proto

package gov.nist.csd.pm.pap.op.prohibition.proto;

public interface DeleteProhibitionOpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteProhibitionOp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
