// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prohibitions.proto

package gov.nist.csd.pm.pap.op.prohibition.proto;

public final class ProhibitionProto {
  private ProhibitionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateProhibitionOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateProhibitionOp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateProhibitionOp_ContainerConditionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateProhibitionOp_ContainerConditionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteProhibitionOp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteProhibitionOp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022prohibitions.proto\"\370\001\n\023CreateProhibiti" +
      "onOp\022\014\n\004name\030\001 \001(\t\022\017\n\007subject\030\002 \001(\t\022\024\n\014s" +
      "ubject_type\030\003 \001(\t\022\r\n\005arset\030\004 \003(\t\022\024\n\014inte" +
      "rsection\030\005 \001(\010\022K\n\024container_conditions\030\006" +
      " \003(\0132-.CreateProhibitionOp.ContainerCond" +
      "itionsEntry\032:\n\030ContainerConditionsEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\010:\0028\001\"#\n\023Delet" +
      "eProhibitionOp\022\014\n\004name\030\001 \001(\tB>\n(gov.nist" +
      ".csd.pm.pap.op.prohibition.protoB\020Prohib" +
      "itionProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateProhibitionOp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateProhibitionOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateProhibitionOp_descriptor,
        new java.lang.String[] { "Name", "Subject", "SubjectType", "Arset", "Intersection", "ContainerConditions", });
    internal_static_CreateProhibitionOp_ContainerConditionsEntry_descriptor =
      internal_static_CreateProhibitionOp_descriptor.getNestedTypes().get(0);
    internal_static_CreateProhibitionOp_ContainerConditionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateProhibitionOp_ContainerConditionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DeleteProhibitionOp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeleteProhibitionOp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteProhibitionOp_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
